import Header from "./components/header/header";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="grid items-start grid-cols-[14rem_1fr]">
        <div className="h-screen p-3 pr-0">
          <Header />
        </div>
        <main className="h-screen p-3">{children}</main>
      </body>
    </html>
  );
}
